#!/bin/bash

function listing {


  cp $2 $3;
  echo "<div class='listingSrcCode'>" >> $3;
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{.javascript .numberLines}" >> $3;
  cat $1 >> $3;
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" >> $3;
  echo "</div>" >> $3;

}


listing ./examples/tip-calculator.js tip-notes.md  ./work/tip-src.md;
listing ./examples/school-data/school-report.mjs school-report-notes.md  ./work/school-report-src.md;


#CHAPTERS="forward.md preface.md way_of_the_program.md variables.md turtles.md functions.md conditionals.md iteration.md lists.md tuples.md dictionaries.md schools.md while.md";

CHAPTERS="forward.md way_of_the_program.md variables.md functions.md ./work/tip-src.md conditionals.md iteration.md while.md strings.md arrays.md ./work/school-report-src.md school-data-exercises.md maps.md code-listings.md preface.md fdl-1.3.md";

pandoc -o ./docs/index.html --mathml --highlight-style zenburn -t html5 --template=tmpl/tmpl.html -s --toc --toc-depth=2 --section-divs -H ./tmpl/style.css $CHAPTERS;

pandoc -o ./docs/tjs.epub --mathml -t epub --template=tmpl/tmpl.html -s --section-divs -H ./tmpl/style.css $CHAPTERS;
